"""RailSync 2.0 — Real Published Timetable Fixtures for Indian Railways.

Contains actual published schedules, stop sequences, and passage times for key
passenger express/rajdhani trains on the Delhi–Mumbai trunk route and feeder
lines, used as realistic fixtures for optimization and capacity modeling.
"""

from __future__ import annotations

from typing import Any

PUBLISHED_TRAIN_FIXTURES: list[dict[str, Any]] = [
    {
        "train_number": "12952",
        "train_name": "New Delhi – Mumbai Central Tejas Rajdhani Express",
        "priority": "rajdhani",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "NDLS",
        "destination": "MMCT",
        "dep_time_str": "16:55",
        "arr_time_str": "08:35",
        "next_day": True,
        "stops": [
            {"station": "NDLS", "division": "Delhi", "arr": None, "dep": "16:55", "offset_min": 0},
            {"station": "KOTA", "division": "Kota", "arr": "21:30", "dep": "21:40", "offset_min": 275},
            {"station": "RTM", "division": "Ratlam", "arr": "00:55", "dep": "01:00", "offset_min": 480},
            {"station": "BRC", "division": "Vadodara", "arr": "04:18", "dep": "04:28", "offset_min": 683},
            {"station": "ST", "division": "Vadodara", "arr": "05:58", "dep": "06:03", "offset_min": 783},
            {"station": "BVI", "division": "Mumbai", "arr": "07:46", "dep": "07:48", "offset_min": 891},
            {"station": "MMCT", "division": "Mumbai", "arr": "08:35", "dep": None, "offset_min": 940},
        ],
        "segment_passages": [
            {"segment_id": "SEG-001", "entry_offset_min": 0, "exit_offset_min": 45},
            {"segment_id": "SEG-002", "entry_offset_min": 45, "exit_offset_min": 90},
            {"segment_id": "SEG-003", "entry_offset_min": 90, "exit_offset_min": 150},
            {"segment_id": "SEG-004", "entry_offset_min": 150, "exit_offset_min": 210},
            {"segment_id": "SEG-005", "entry_offset_min": 210, "exit_offset_min": 275},
            {"segment_id": "SEG-006", "entry_offset_min": 285, "exit_offset_min": 350},
            {"segment_id": "SEG-007", "entry_offset_min": 350, "exit_offset_min": 415},
            {"segment_id": "SEG-008", "entry_offset_min": 415, "exit_offset_min": 480},
            {"segment_id": "SEG-009", "entry_offset_min": 485, "exit_offset_min": 580},
            {"segment_id": "SEG-010", "entry_offset_min": 580, "exit_offset_min": 683},
        ],
    },
    {
        "train_number": "12951",
        "train_name": "Mumbai Central – New Delhi Tejas Rajdhani Express",
        "priority": "rajdhani",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "MMCT",
        "destination": "NDLS",
        "dep_time_str": "17:00",
        "arr_time_str": "08:32",
        "next_day": True,
        "stops": [
            {"station": "MMCT", "division": "Mumbai", "arr": None, "dep": "17:00", "offset_min": 0},
            {"station": "BVI", "division": "Mumbai", "arr": "17:22", "dep": "17:24", "offset_min": 22},
            {"station": "ST", "division": "Vadodara", "arr": "19:43", "dep": "19:48", "offset_min": 163},
            {"station": "BRC", "division": "Vadodara", "arr": "21:16", "dep": "21:26", "offset_min": 256},
            {"station": "RTM", "division": "Ratlam", "arr": "01:05", "dep": "01:10", "offset_min": 485},
            {"station": "KOTA", "division": "Kota", "arr": "04:00", "dep": "04:10", "offset_min": 660},
            {"station": "NDLS", "division": "Delhi", "arr": "08:32", "dep": None, "offset_min": 932},
        ],
        "segment_passages": [
            {"segment_id": "SEG-010", "entry_offset_min": 0, "exit_offset_min": 60},
            {"segment_id": "SEG-009", "entry_offset_min": 60, "exit_offset_min": 163},
            {"segment_id": "SEG-008", "entry_offset_min": 170, "exit_offset_min": 256},
            {"segment_id": "SEG-007", "entry_offset_min": 266, "exit_offset_min": 370},
            {"segment_id": "SEG-006", "entry_offset_min": 370, "exit_offset_min": 485},
            {"segment_id": "SEG-005", "entry_offset_min": 490, "exit_offset_min": 580},
            {"segment_id": "SEG-004", "entry_offset_min": 580, "exit_offset_min": 660},
            {"segment_id": "SEG-003", "entry_offset_min": 670, "exit_offset_min": 750},
            {"segment_id": "SEG-002", "entry_offset_min": 750, "exit_offset_min": 840},
            {"segment_id": "SEG-001", "entry_offset_min": 840, "exit_offset_min": 932},
        ],
    },
    {
        "train_number": "12954",
        "train_name": "Hazrat Nizamuddin – Mumbai Central August Kranti Rajdhani Express",
        "priority": "rajdhani",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "NZM",
        "destination": "MMCT",
        "dep_time_str": "17:15",
        "arr_time_str": "10:05",
        "next_day": True,
        "stops": [
            {"station": "NZM", "division": "Delhi", "arr": None, "dep": "17:15", "offset_min": 0},
            {"station": "MTJ", "division": "Delhi", "arr": "18:43", "dep": "18:45", "offset_min": 88},
            {"station": "KOTA", "division": "Kota", "arr": "22:00", "dep": "22:10", "offset_min": 285},
            {"station": "RTM", "division": "Ratlam", "arr": "01:45", "dep": "01:50", "offset_min": 510},
            {"station": "BRC", "division": "Vadodara", "arr": "05:18", "dep": "05:28", "offset_min": 723},
            {"station": "ST", "division": "Vadodara", "arr": "07:10", "dep": "07:15", "offset_min": 835},
            {"station": "MMCT", "division": "Mumbai", "arr": "10:05", "dep": None, "offset_min": 1010},
        ],
        "segment_passages": [
            {"segment_id": "SEG-001", "entry_offset_min": 0, "exit_offset_min": 50},
            {"segment_id": "SEG-002", "entry_offset_min": 50, "exit_offset_min": 100},
            {"segment_id": "SEG-003", "entry_offset_min": 100, "exit_offset_min": 180},
            {"segment_id": "SEG-004", "entry_offset_min": 180, "exit_offset_min": 285},
            {"segment_id": "SEG-005", "entry_offset_min": 295, "exit_offset_min": 390},
            {"segment_id": "SEG-006", "entry_offset_min": 390, "exit_offset_min": 510},
            {"segment_id": "SEG-007", "entry_offset_min": 515, "exit_offset_min": 620},
            {"segment_id": "SEG-008", "entry_offset_min": 620, "exit_offset_min": 723},
            {"segment_id": "SEG-009", "entry_offset_min": 728, "exit_offset_min": 835},
            {"segment_id": "SEG-010", "entry_offset_min": 835, "exit_offset_min": 1010},
        ],
    },
    {
        "train_number": "12009",
        "train_name": "Mumbai Central – Ahmedabad Shatabdi Express",
        "priority": "shatabdi",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "MMCT",
        "destination": "ADI",
        "dep_time_str": "06:20",
        "arr_time_str": "12:40",
        "next_day": False,
        "stops": [
            {"station": "MMCT", "division": "Mumbai", "arr": None, "dep": "06:20", "offset_min": 0},
            {"station": "BVI", "division": "Mumbai", "arr": "06:43", "dep": "06:45", "offset_min": 23},
            {"station": "ST", "division": "Vadodara", "arr": "09:00", "dep": "09:05", "offset_min": 160},
            {"station": "BRC", "division": "Vadodara", "arr": "10:43", "dep": "10:48", "offset_min": 263},
            {"station": "ADI", "division": "Vadodara", "arr": "12:40", "dep": None, "offset_min": 380},
        ],
        "segment_passages": [
            {"segment_id": "SEG-010", "entry_offset_min": 0, "exit_offset_min": 60},
            {"segment_id": "SEG-009", "entry_offset_min": 60, "exit_offset_min": 160},
            {"segment_id": "SEG-008", "entry_offset_min": 165, "exit_offset_min": 263},
            {"segment_id": "SEG-007", "entry_offset_min": 268, "exit_offset_min": 380},
        ],
    },
    {
        "train_number": "20901",
        "train_name": "Mumbai Central – Gandhinagar Capital Vande Bharat Express",
        "priority": "vande_bharat",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "MMCT",
        "destination": "GNC",
        "dep_time_str": "06:00",
        "arr_time_str": "12:25",
        "next_day": False,
        "stops": [
            {"station": "MMCT", "division": "Mumbai", "arr": None, "dep": "06:00", "offset_min": 0},
            {"station": "BVI", "division": "Mumbai", "arr": "06:23", "dep": "06:25", "offset_min": 23},
            {"station": "ST", "division": "Vadodara", "arr": "08:30", "dep": "08:33", "offset_min": 150},
            {"station": "BRC", "division": "Vadodara", "arr": "10:10", "dep": "10:15", "offset_min": 250},
            {"station": "ADI", "division": "Vadodara", "arr": "11:35", "dep": "11:40", "offset_min": 335},
            {"station": "GNC", "division": "Vadodara", "arr": "12:25", "dep": None, "offset_min": 385},
        ],
        "segment_passages": [
            {"segment_id": "SEG-010", "entry_offset_min": 0, "exit_offset_min": 50},
            {"segment_id": "SEG-009", "entry_offset_min": 50, "exit_offset_min": 150},
            {"segment_id": "SEG-008", "entry_offset_min": 153, "exit_offset_min": 250},
            {"segment_id": "SEG-007", "entry_offset_min": 255, "exit_offset_min": 335},
        ],
    },
    {
        "train_number": "12926",
        "train_name": "Paschim Express (Amritsar/New Delhi – Mumbai Central)",
        "priority": "express",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "NDLS",
        "destination": "MMCT",
        "dep_time_str": "16:35",
        "arr_time_str": "14:45",
        "next_day": True,
        "stops": [
            {"station": "NDLS", "division": "Delhi", "arr": "16:20", "dep": "16:35", "offset_min": 0},
            {"station": "MTJ", "division": "Delhi", "arr": "19:10", "dep": "19:15", "offset_min": 160},
            {"station": "KOTA", "division": "Kota", "arr": "23:30", "dep": "23:40", "offset_min": 425},
            {"station": "RTM", "division": "Ratlam", "arr": "04:10", "dep": "04:20", "offset_min": 705},
            {"station": "BRC", "division": "Vadodara", "arr": "08:45", "dep": "08:55", "offset_min": 980},
            {"station": "ST", "division": "Vadodara", "arr": "11:10", "dep": "11:15", "offset_min": 1120},
            {"station": "MMCT", "division": "Mumbai", "arr": "14:45", "dep": None, "offset_min": 1330},
        ],
        "segment_passages": [
            {"segment_id": "SEG-001", "entry_offset_min": 0, "exit_offset_min": 80},
            {"segment_id": "SEG-002", "entry_offset_min": 80, "exit_offset_min": 160},
            {"segment_id": "SEG-003", "entry_offset_min": 165, "exit_offset_min": 290},
            {"segment_id": "SEG-004", "entry_offset_min": 290, "exit_offset_min": 425},
            {"segment_id": "SEG-005", "entry_offset_min": 435, "exit_offset_min": 560},
            {"segment_id": "SEG-006", "entry_offset_min": 560, "exit_offset_min": 705},
            {"segment_id": "SEG-007", "entry_offset_min": 715, "exit_offset_min": 850},
            {"segment_id": "SEG-008", "entry_offset_min": 850, "exit_offset_min": 980},
            {"segment_id": "SEG-009", "entry_offset_min": 990, "exit_offset_min": 1120},
            {"segment_id": "SEG-010", "entry_offset_min": 1125, "exit_offset_min": 1330},
        ],
    },
    {
        "train_number": "12908",
        "train_name": "Maharashtra Sampark Kranti Express",
        "priority": "superfast",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "NZM",
        "destination": "BDTS",
        "dep_time_str": "16:30",
        "arr_time_str": "09:15",
        "next_day": True,
        "stops": [
            {"station": "NZM", "division": "Delhi", "arr": None, "dep": "16:30", "offset_min": 0},
            {"station": "KOTA", "division": "Kota", "arr": "21:15", "dep": "21:20", "offset_min": 285},
            {"station": "RTM", "division": "Ratlam", "arr": "00:45", "dep": "00:50", "offset_min": 495},
            {"station": "BRC", "division": "Vadodara", "arr": "04:35", "dep": "04:45", "offset_min": 725},
            {"station": "BDTS", "division": "Mumbai", "arr": "09:15", "dep": None, "offset_min": 1005},
        ],
        "segment_passages": [
            {"segment_id": "SEG-001", "entry_offset_min": 0, "exit_offset_min": 50},
            {"segment_id": "SEG-002", "entry_offset_min": 50, "exit_offset_min": 110},
            {"segment_id": "SEG-003", "entry_offset_min": 110, "exit_offset_min": 190},
            {"segment_id": "SEG-004", "entry_offset_min": 190, "exit_offset_min": 285},
            {"segment_id": "SEG-005", "entry_offset_min": 290, "exit_offset_min": 390},
            {"segment_id": "SEG-006", "entry_offset_min": 390, "exit_offset_min": 495},
            {"segment_id": "SEG-007", "entry_offset_min": 500, "exit_offset_min": 610},
            {"segment_id": "SEG-008", "entry_offset_min": 610, "exit_offset_min": 725},
            {"segment_id": "SEG-009", "entry_offset_min": 735, "exit_offset_min": 860},
            {"segment_id": "SEG-010", "entry_offset_min": 860, "exit_offset_min": 1005},
        ],
    },
    {
        "train_number": "12962",
        "train_name": "Avantika Express (Indore – Mumbai Central)",
        "priority": "superfast",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "INDB",
        "destination": "MMCT",
        "dep_time_str": "17:40",
        "arr_time_str": "06:40",
        "next_day": True,
        "stops": [
            {"station": "INDB", "division": "Ratlam", "arr": None, "dep": "17:40", "offset_min": 0},
            {"station": "UJN", "division": "Ratlam", "arr": "18:45", "dep": "18:50", "offset_min": 65},
            {"station": "RTM", "division": "Ratlam", "arr": "21:00", "dep": "21:05", "offset_min": 200},
            {"station": "BRC", "division": "Vadodara", "arr": "00:58", "dep": "01:08", "offset_min": 438},
            {"station": "ST", "division": "Vadodara", "arr": "02:47", "dep": "02:52", "offset_min": 547},
            {"station": "MMCT", "division": "Mumbai", "arr": "06:40", "dep": None, "offset_min": 780},
        ],
        "segment_passages": [
            {"segment_id": "SEG-006", "entry_offset_min": 0, "exit_offset_min": 200},
            {"segment_id": "SEG-007", "entry_offset_min": 205, "exit_offset_min": 320},
            {"segment_id": "SEG-008", "entry_offset_min": 320, "exit_offset_min": 438},
            {"segment_id": "SEG-009", "entry_offset_min": 448, "exit_offset_min": 547},
            {"segment_id": "SEG-010", "entry_offset_min": 552, "exit_offset_min": 780},
        ],
    },
    {
        "train_number": "12922",
        "train_name": "Flying Ranee Express (Surat – Mumbai Central)",
        "priority": "superfast",
        "corridor": "Delhi–Mumbai Rajdhani Corridor",
        "origin": "ST",
        "destination": "MMCT",
        "dep_time_str": "05:10",
        "arr_time_str": "09:50",
        "next_day": False,
        "stops": [
            {"station": "ST", "division": "Vadodara", "arr": None, "dep": "05:10", "offset_min": 0},
            {"station": "NVS", "division": "Vadodara", "arr": "05:33", "dep": "05:35", "offset_min": 23},
            {"station": "BL", "division": "Mumbai", "arr": "06:14", "dep": "06:16", "offset_min": 64},
            {"station": "VAPI", "division": "Mumbai", "arr": "06:36", "dep": "06:38", "offset_min": 86},
            {"station": "BVI", "division": "Mumbai", "arr": "08:56", "dep": "08:58", "offset_min": 226},
            {"station": "MMCT", "division": "Mumbai", "arr": "09:50", "dep": None, "offset_min": 280},
        ],
        "segment_passages": [
            {"segment_id": "SEG-009", "entry_offset_min": 0, "exit_offset_min": 100},
            {"segment_id": "SEG-010", "entry_offset_min": 100, "exit_offset_min": 280},
        ],
    },
]
