/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dfe9f5",
        "tertiary": "#001404",
        "on-primary": "#ffffff",
        "on-primary-container": "#7e8ca9",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#3c9e57",
        "on-background": "#131d25",
        "surface-dim": "#d1dbe7",
        "on-secondary-fixed": "#101c2e",
        "secondary-fixed-dim": "#bbc7df",
        "on-error": "#ffffff",
        "surface-tint": "#505f7a",
        "on-tertiary-fixed-variant": "#005323",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dae3f0",
        "on-primary-fixed-variant": "#394761",
        "secondary-container": "#d4e0f9",
        "tertiary-fixed-dim": "#79db8d",
        "surface-bright": "#f7f9ff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b8c7e6",
        "on-secondary-fixed-variant": "#3c475b",
        "surface": "#f7f9ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#16253d",
        "surface-container": "#e5effb",
        "surface-container-low": "#ecf4ff",
        "secondary": "#535f74",
        "inverse-surface": "#28313b",
        "secondary-fixed": "#d7e3fc",
        "outline-variant": "#c5c6ce",
        "background": "#f7f9ff",
        "primary": "#011027",
        "inverse-on-surface": "#e8f2fe",
        "on-surface-variant": "#44474d",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#0c1c33",
        "on-tertiary-fixed": "#00210a",
        "inverse-primary": "#b8c7e6",
        "on-secondary-container": "#576378",
        "on-surface": "#131d25",
        "tertiary-fixed": "#95f8a7",
        "surface-variant": "#dae3f0",
        "tertiary-container": "#002c0f",
        "outline": "#75777e",
        "primary-fixed": "#d6e3ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-dense": "0.5rem",
        "gutter": "0.75rem",
        "space-sm": "0.375rem",
        "space-lg": "0.75rem",
        "margin": "1rem",
        "space-xs": "0.25rem",
        "space-md": "0.5rem",
        "space-xl": "1rem"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "code-lg": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "code-lg": ["14px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["15px", { "lineHeight": "20px", "fontWeight": "600" }],
        "headline-xl": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "code-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "500" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "code-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
